config/routes.rb
Rails.application.routes.draw do
  mount Porthos::Middleware::TagsAutocompleteApp.instance => '/admin/tags/autocomplete'

  filter :url_resolver

  resources :pages do
    collection do
      get 'categories'
    end
    member do
      get 'preview'
    end
  end
  get 'pages/:id/category' => 'pages#category', :as => 'pages_category'

  namespace :admin do
    root :to => 'dashboard#index'
    get '/login' => 'sessions#new', :as => 'login'
    get '/logout' => 'sessions#destroy', :as => 'logout'
    resources :sessions
    resources :users do
      collection do
        get 'admins'
        get 'search'
      end
    end

    resources :site_settings
    resources :redirects
    resources :tags
    resources :display_options do
      collection do
        put :sort
      end
    end

    resources :nodes do
      member do
        get "place"
        put "toggle"
        get "confirm_delete"
      end
      collection do
        put "sort"
      end
    end

    resources :link_lists do
      resources :links do
        collection do
          put 'sort'
        end
      end
    end

    resources :templates do
      resources :datum_templates do
        collection do
          put 'sort'
        end
      end
    end
    resources :page_templates do
      collection do
        put 'sort'
      end
    end
    resources :content_templates do
      collection do
        put 'sort'
      end
    end

    resources :items do
      collection do
        get "search"
        put "sort"
      end
      member do
        put "toggle"
        put "publish"
        get "confirm_delete"
      end
      resources :data do
        collection do
          put "sort"
        end
        member do
          put "toggle"
          get "settings"
        end
      end
    end

    resources :assets do
      collection do
        get 'search'
        get 'incomplete'
        put 'update_multiple'
      end
      member do
        get 'edit_cropping'
      end
    end
  end
end

app/views/admin/pages/_asset_association.html.erb
<%= form_for datum, :as => :datum, :url => admin_page_datum_path(@page, datum), :html => { :class => 'datum_edit image_form', :id => "datum_#{datum.id}_edit" } do |f| %>
  <% if datum._parent_document.is_a?(DatumCollection) %>
  <%= hidden_field_tag 'parent_id', datum._parent_document.id %>
  <% end %>
  <%= render :partial => 'admin/data/asset_association_form', :locals => { :f => f, :datum => datum } %>
<% end %>

app/views/admin/pages/index.html.erb
<% @page_title = 'Sidor' -%>
<% @page_class = 'layout3' -%>
<%= render :partial => 'admin/pages/sub_nav' %>
<% (@page_template && @page_template.pages_sortable?).tap do |sortable| %>
<div id="workspace">
  <div class="header">
    <% if @page_template %>
    <h1><%= @page_template.label %></h1>
    <% else %>
    <h1><%= t('.all_pages') %></h1>
    <% end %>
  </div>
  <div class="tools">
    <% if @page_template %>
    <div class="add">
      <%= link_to t('.create_new', :template => @page_template.label.downcase), new_admin_page_path(:page_template_id => @page_template.id), :class => 'new' %>
    </div>
    <% end %>
  <% unless sortable %>
    <%= form_tag admin_pages_path, :method => :get do |f| %>
    <div class="sort">
      <label for="filters_order_by">Sortering:</label>
      <% current_scopes.except(:order_by).each do |filter, value| -%>
        <%= hidden_field_tag filter, value %>
      <% end -%>
        <%= select_tag 'order_by', options_for_select({ 'Senast ändrad' => 'updated_at desc', 'Publicerad' => 'published_on desc', 'A-Z' => 'title asc' }, current_scopes[:order_by]) %>
    </div>
    <% end %>
  <% end %>
  </div>
  <div id="content">
    <div class="tablewrap">
      <% if @page_template && !@page_template.allow_node_placements? && !@page_template.section %>
      <div class="section">
        <%= link_to t('.add_section'), new_admin_page_path(type: 'Section', page_template_id: @page_template.id) %>
      </div>
      <% end %>
      <table class="pages <%= ' sortable' if sortable %>">
        <thead>
          <tr>
            <% if sortable %>
            <th class="sort"></th>
            <% end %>
            <th><%= Page.human_attribute_name(:title) %></th>
            <th><%= Page.human_attribute_name(:updated_at) %></th>
            <th><%= t(:status) %></th>
          </tr>
        </thead>
        <% if @page_template && @page_template.section %>
        <% @page_template.section.tap do |section| %>
        <tbody class="section">
          <%= render partial: 'row', locals: { page: section, sortable: sortable } %>
        </tbody>
        <% end %>
        <% end %>
        <% if sortable %>
        <%= tag 'tbody', :'data-sort-uri' => sort_admin_pages_path, :id => 'pages' %>
        <% else %>
        <tbody>
        <% end %>
        <% @pages.each do |page| %>
          <%= render partial: 'row', locals: { page: page, sortable: sortable } %>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= paginate @pages if @pages.any? %>
  </div>
</div>
<% end %>

app/views/admin/pages/search.html.erb
<% @page_title = 'Sidor' -%>
<% @page_class = 'layout3' -%>
<%= render :partial => 'admin/pages/sub_nav' %>
<div id="workspace">
  <div class="header">
    <h1>Sökresultat för ”<%= @query %>”</h1>
  </div>
  <div class="tools">
    <div class="add">
      Lägg till:
      <% @page_templates.each do |page_template| -%>
        <%= link_to page_template.label, (!current_scopes[:with_parent] ? new_admin_page_path(:page => { :page_template_id => page_template.id }) : new_admin_page_path(:page => { :page_template_id => page_template, :parent_id => current_scopes[:with_parent].split(',')[0], :parent_type => current_scopes[:with_parent].split(',')[1] })), :class => 'new' %>
      <% end if @page_templates.any? %>
    </div>
  </div>
  <div id="content">
    <ul class="items">
    <% @pages.each do |page| %>
      <li>
        <%= render :partial => page.template.views.admin_in_list, :locals => { :page => page } %>
      </li>
    <% end %>
    </ul>
    <%= paginate @pages if @pages.any? %>
  </div>
</div>