config/routes.rb
Rails.application.routes.draw do
  mount Porthos::Middleware::TagsAutocompleteApp.instance => '/admin/tags/autocomplete'

  filter :url_resolver

  resources :pages do
    collection do
      get 'categories'
    end
    member do
      get 'preview'
    end
  end
  get 'pages/:id/category' => 'pages#category', :as => 'pages_category'

  namespace :admin do
    root :to => 'dashboard#index'
    get '/login' => 'sessions#new', :as => 'login'
    get '/logout' => 'sessions#destroy', :as => 'logout'
    resources :sessions
    resources :users do
      collection do
        get 'admins'
        get 'search'
      end
    end

    resources :site_settings
    resources :redirects
    resources :tags
    resources :display_options do
      collection do
        put :sort
      end
    end

    resources :nodes do
      member do
        get "place"
        put "toggle"
        get "confirm_delete"
      end
      collection do
        put "sort"
      end
    end

    resources :link_lists do
      resources :links do
        collection do
          put 'sort'
        end
      end
    end

    resources :templates do
      resources :datum_templates do
        collection do
          put 'sort'
        end
      end
    end
    resources :page_templates do
      collection do
        put 'sort'
      end
    end
    resources :content_templates do
      collection do
        put 'sort'
      end
    end

    resources :items do
      collection do
        get "search"
        put "sort"
      end
      member do
        put "toggle"
        put "publish"
        get "confirm_delete"
      end
      resources :data do
        collection do
          put "sort"
        end
        member do
          put "toggle"
          get "settings"
        end
      end
    end

    resources :assets do
      collection do
        get 'search'
        get 'incomplete'
        put 'update_multiple'
      end
      member do
        get 'edit_cropping'
      end
    end
  end
end

app/models/asset.rb
class Asset
  include MongoMapper::Document
  plugin MongoMapper::Plugins::IdentityMap

  include Tanker

  taggable

  key :name, String
  key :extension, String
  key :mime_type, String
  key :filetype, String
  key :size, Integer
  key :title, String
  key :author, String
  key :description, String
  key :reference_number, String
  key :hidden, Boolean, default: -> { false }
  key :created_by_id, ObjectId
  key :_usages, Array, default: -> { [] }
  timestamps!

  tankit Porthos.config.tanking.index_name, :as => 'Asset' do
    indexes :name
    indexes :title
    indexes :author
    indexes :description
    indexes :reference_number
    indexes :tag_names
    indexes :hidden
  end

  class_attribute :filetypes
  self.filetypes = {
    :image => %w(jpg jpeg png gif tiff tif),
    :video => %w(flv mov qt mpg avi mp4),
    :sound => %w(mp3 wav aiff aif),
    :pdf   => %w(pdf),
    :document => []
  }

  belongs_to :created_by, class_name: "User"

  scope :is_hidden, ->(hidden) { where(hidden: hidden) }

  scope :created_by, ->(user_id) { where(created_by_id: user_id) }

  scope :by_type, ->(type) { where(_type: type) }

  scope :by_filetype, ->(filetype) { where(filetype: filetype) }

  scope :by_extension, ->(extension) {
    if extension.is_a?(Array)
      where(:extension.in => extension)
    else
      where(extension: extension)
    end
  }

  scope :order_by, ->(order) { sort(order) }

  attr_accessor :file
  validates_presence_of :file, :if => :new_record?

  before_validation :process
  after_destroy :cleanup

  after_save proc { |asset| asset.delay.update_tank_indexes }
  after_destroy proc { |asset| asset.delete_tank_indexes }

  def self.default_filetype
    filetypes.keys.detect do |key|
      filetypes[key].empty?
    end.to_s
  end

  def full_name
    @full_name ||= "#{name}.#{extension}"
  end

  def remote_url
    @remote_url ||= Porthos.s3_storage.url(full_name)
  end

  def of_the_type(filetype)
    type = self.filetypes[filetype.to_sym]
    type && type.include?(self.extension)
  end

  def usages
    @usages ||= AssetUsages.new(self)
  end

  def remove_usage object, context
    usages.remove object, context
  end

  def add_usage object, context
    usages.add object, context
  end

  def touch_usages
    usages.each &:touch
  end

  class << self
    def uploaders
      User.find(self.fields(:created_by_id).distinct(:created_by_id))
    end

    def from_upload(attrs)
      extension = File.extname(attrs[:file].original_filename.downcase).gsub(/\./,'')
      if filetypes[:image].include?(extension)
        klass = ImageAsset
      else
        klass = Asset
      end
      klass.new(attrs)
    end

    def filetype_for_extension(_extension)
      Asset.default_filetype.tap do |_filetype|
        filetypes.each { |key, extensions| _filetype.replace(key.to_s) and break if extensions.include?(_extension) }
      end
    end
  end

  protected

  def process
    if file.present?
      extract_attributes_from_file
      ensure_unique_name

      cleanup unless new_record?

      store
    end
  end

  def extract_attributes_from_file
    self.size      = file.size
    self.mime_type = MIME::Types.type_for(file.original_filename).first.to_s
    self.extension = File.extname(file.original_filename).gsub(/\./,'').gsub(/\?.*/,'').downcase
    file.original_filename.gsub(".#{read_attribute(:extension)}",'').tap do |original_filename|
      self.name    = original_filename.parameterize.to_s unless self.name.present?
      self.title   = original_filename unless self.title.present?
    end
    self.filetype = Asset.filetype_for_extension(extension)
  end

  def ensure_unique_name
    while !Asset.where(:name => self.name).count.zero? do
      self.name = "#{self.name}_#{SecureRandom.hex(8)}"
    end
  end

  def store
    unless Porthos.s3_storage.store(file, full_name)
      errors[:file] << t(:unable_to_store)
    end
    File.unlink(file.path) if file.respond_to?(:path)
  end

  # after destroy
  def cleanup
    Porthos.s3_storage.destroy(full_name)
  end
end

app/controllers/admin/assets_controller.rb
class Admin::AssetsController < ApplicationController
  respond_to :html
  include Porthos::Admin
  before_filter :set_callback,
                :only => [:index, :search]
  before_filter :find_tags,
                :only => [:index, :new]
  skip_before_filter :clear_callback

  protect_from_forgery :only => :create

  has_scope :is_hidden, :default => false
  has_scope :created_by
  has_scope :by_type
  has_scope :by_filetype, :type => :array
  has_scope :by_extension, :type => :array
  has_scope :order_by, :default => 'created_at DESC'

  def index
    @tags = Asset.tags_by_count
    @assets = unless @current_tags.any?
      apply_scopes(Asset).page(params[:page])
    else
      Asset.tagged_with(params[:tags]).where(:hidden => false).sort(:created_at.desc).page(params[:page])
    end
    respond_with(@assets)
  end

  def search
    @type = params[:type] ? params[:type] : 'Asset'
    @tags = Asset.tags_by_count(:limit => 30)
    unless params[:query].blank?
      @query = params[:query]
      page = params[:page] || 1
      per_page = params[:per_page] ? params[:per_page].to_i : 45
      @assets = Asset.search_tank(@query, :conditions => {'hidden' => false}, :per_page => per_page, :page => page)
      respond_to do |format|
        format.html do
          @current_tags = params[:tags] || []
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to admin_assets_path }
      end
    end
  end

  def new
    @asset = Asset.new
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def create
    @assets = if params[:asset][:file].is_a?(Array)
      params[:asset][:file].collect do |file|
        Asset.from_upload(:file => file, :created_by => current_user)
      end
    else
      [Asset.from_upload(params[:asset].merge({:created_by => current_user}))]
    end
    @not_saved = @assets.collect { |a| a.save }.include? false
    respond_to do |format|
      unless @not_saved
        flash[:notice] = t(:saved, :scope => [:app, :admin_assets])
        format.html { redirect_to incomplete_admin_assets_url(:assets => @assets.collect {|asset| asset.id }) }
        format.json do
          render :text => @assets.to_json, :layout => false, :status => 200
        end
      else
        @asset = @assets.first
        format.html { render :action => "new" }
      end
    end
  end

  def incomplete
    @assets = Asset.find(params[:assets])
  end

  def update_multiple
    params[:assets].each do |asset|
      save_asset = Asset.find(asset[0])
      save_asset.update_attributes(asset[1])
    end
    flash[:notice] = t(:saved, :scope => [:app, :admin_assets])
    respond_to do |format|
      format.html { redirect_to admin_assets_url }
    end
  end

  def update
    @asset = Asset.find(params[:id])
    if @asset.update_attributes(params[:asset])
      @asset.touch_usages
      flash[:notice] = "#{@asset.full_name} #{t(:saved, :scope => [:app, :admin_general])}"
    end
    respond_with @asset, :location => (params[:return_to] || edit_admin_asset_url(@asset))
  end

  def destroy
    @asset = Asset.find_by_name(params[:id]) || Asset.find(params[:id])
    @asset.destroy
    flash[:notice] = "#{@asset.full_name} #{t(:deleted, :scope => [:app, :admin_general])}"
    respond_with @asset, :location => (params[:return_to] || admin_assets_path)
  end

  def edit_cropping
    @asset = Asset.find_by_name(params[:id]) || Asset.find(params[:id])
    @cropping = (@asset.versions[params[:cropping]] || {}).tap do |c|
      c[:width], c[:height] = params[:cropping].gsub('c','').split('x')
    end
  end

protected

  def find_tags
    @tags = Asset.tags_by_count(:limit => 30)
    @current_tags = params[:tags] || []
  end

  def set_callback
    @create_callback = if params[:create_callback]
      session[:create_callback] = params[:create_callback]
    elsif session[:create_callback]
      session[:create_callback]
    end
  end

end

app/views/admin/assets/_sub_nav.html.erb
<div id="sub_nav">
<% if Rails.application.config.use_fulltext_search %>
  <%= form_for :asset, :url => search_admin_assets_path(:type => params[:type]), :html => { :method => :get } do |f| %>
    <div class="search fullwidth">
      <%= text_field_tag :query, @query, :placeholder => 'Sök efter filer', :class => "search_query", :id=> "search_query", :autocomplete => 'off' %>
      <%= submit_tag "Sök", :style => "display:none" %>
    </div>
  <% end %>
<% end %>
  <div class="label">Uppladdad av</div>
  <ul class="filter">
    <li<%= ' class="current"'.html_safe unless current_scopes[:by_extension] %>>
      <%= link_to "Alla", admin_assets_path(current_scopes.except(:by_extension))%>
    </li>
  <% Asset.filetypes.each do |key, extensions| %>
    <li<%= ' class="current"'.html_safe if current_scopes[:by_extension] == extensions %>>
      <%= link_to I18n.t(key), admin_assets_path(current_scopes.merge(:by_extension => extensions)) %>
    </li>
  <% end %>
  </ul>
  <div class="label">Uppladdad av</div>
  <ul class="filter">
    <li<%= ' class="current"'.html_safe unless current_scopes[:created_by] %>>
      <%= link_to "Alla", admin_assets_path(current_scopes.except(:created_by)) %>
    </li>
    <% Asset.uploaders.sort_by(&:first_name).each do |user| -%>
      <li<%= ' class="current"'.html_safe if current_scopes[:created_by] == user.id.to_s %>>
        <%= link_to user.short_name, admin_assets_path(current_scopes.merge(:created_by => user.id)) %>
      </li>
    <% end %>
  </ul>
<% if @tags.present? and @tags.any? -%>
  <div class="label">Nyckelord</div>
  <ul class="tags alphabetical">
  <% @tags.sort_by(&:name).group_by { |tag| tag.name[0...1].upcase }.each do |first_letter, tags| -%>
    <li>
      <span class="letter"><%= first_letter %></span>
      <% tags.each do |tag| -%>
        <%= !@current_tags.include?(tag.name) ? link_to("#{tag.name.downcase}", admin_assets_path(:tags => (params[:tags] || []).dup.push(tag.name)), :class => 'tag') : link_to("#{tag.name.downcase}", admin_assets_path(:tags => (params[:tags].dup - [tag.name])), :class => 'tag current') -%><%= ', ' unless tag == tags.last -%>
      <% end -%>
    </li>
  <% end -%>
  </ul>
<% end -%>
</div>

app/views/admin/assets/create.html.erb
<% @page_title = "Filarkiv" %>
<% @page_class = "AB" %>
<h1>Filer och dokument</h1>
<div id="content">
  <div id="c-b">
  </div>
  <div id="c-a">
    <h2 class="label">Nya filer</h2>
  </div>
</div>

app/views/admin/assets/edit.html.erb
<% @page_title = "Ändra fil: #{@asset.title}" %>
<% @page_class = 'layout3' %>
<%= render :partial => 'admin/assets/sub_nav' %>
<div id="workspace">
  <div class="header">
    <h1><span class="pre">Ändra filen</span> <%= @asset.title %></h1>
  </div>
  <div id="content">
    <div id="c_1"><div class="inner">
      <%= form_for [:admin, @asset], as: :asset, url: admin_asset_path(@asset), html: { id: "asset_form" } do |f| %>
        <% if params[:return_to] %>
        <%= hidden_field_tag :return_to, params[:return_to] %>
        <% end %>
        <fieldset>
          <label for="asset_title">Titel</label>
          <div class="fullwidth">
            <%= f.text_field "title", :size => 40, :class => "title" %>
            <p class="form_help after">Skriv vad bilden/filmen/dokumentet föreställer. Används som alternativ text när bilder inte visas.</p>
          </div>
          <label for="asset_description">Beskrivning</label>
          <div class="fullwidth"><%= f.text_area "description", :class => 'descripition', :rows => 6, :cols => 40 %></div>
          <label for="asset_author">Fotograf/copyright</label>
          <div class="fullwidth"><%= f.text_field "author", :size => 50 %></div>
          <label for="asset_reference_number">Referensnummer</label>
          <div class="fullwidth"><%= f.text_field "reference_number", :size => 50 %></div>
          <label for="asset_tag_names">Nyckelord <span class="form_help">dela flera nyckelord med mellanslag</span></label>
          <div class="fullwidth"><%= f.text_field :tag_names, :class => 'asset_tags', :size => 50 %></div>

          <% if @asset.is_a? ImageAsset %>
            <label for="asset_file">Ändra bildfil</label>
            <%= f.file_field :file, size: 15, accept: "image/*" %>
          <% end %>
        </fieldset>
        <fieldset class="submit">
          <%= submit_tag I18n.t(:save) %> <%= I18n.t(:or) %> <%= link_to I18n.t(:cancel), previous_view_path(admin_assets_path) %>
        </fieldset>
      <% end %>
    </div></div>
    <div id="c_2"><div class="inner">
      <div class="asset<%= " #{@asset.class}" %>">
        <% if @asset.is_a?(ImageAsset) %>
          <%= image_tag @asset.version_url(:size => '320'), :id => "asset_#{@asset.id}" %>
        <% else %>
          <span class="icon"></span>
        <% end %>
      </div>
      <table class="meta">
        <tbody>
          <tr>
            <th scope="row">Uppladdad</th>
            <td><%= @asset.created_at.strftime("%d %B %Y") %></td>
          </tr>
          <tr>
            <th scope="row">Filnamn</th>
            <td><%= "#{@asset.name}.#{@asset.extension}" %></td>
          </tr>
          <% if @asset.is_a?(ImageAsset) %>
          <tr>
            <th>Format</th>
            <td><%= [@asset.width, @asset.height].join('x') %></td>
          </tr>
          <% end %>
          <tr>
            <th scope="row">Storlek</th>
            <td><%= number_to_human_size(@asset.size) %></td>
          </tr>
          <tr>
          <% if @asset.is_a?(ImageAsset) %>
            <td colspan="2"><%= link_to "Ladda ned original", @asset.remote_url(cdn_host: false) %></td>
          <% else %>
            <td colspan="2"><%= link_to "Ladda ned original", @asset.remote_url %></td>
          <% end %>
          </tr>
        </tbody>
      </table>
      <% if @asset.respond_to?(:versions) and @asset.versions.any? %>
      <div class="versions">
        <h2>Beskärningar</h2>
        <ul>
        <% @asset.versions.keys.each do |cropping| %>
          <li><%= link_to cropping, edit_cropping_admin_asset_path(@asset,
            :cropping => cropping,
            :return_to => params[:return_to]) %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
      <% if @asset.usages.any? %>
      <div class="usages">
        <h2>Används på:</h2>
        <ul>
        <% @asset.usages.each do |usage| %>
          <li>
            <% if usage.is_a?(Item) %>
              <%= link_to usage.title, admin_item_path(usage) %>
            <% else %>
              <%= link_to usage.name, [:admin, usage] %>
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
      <% end %>
    </div></div>
  </div>
</div>

app/views/admin/assets/edit_cropping.html.erb
<% @page_title = "Ändra beskärning: #{@asset.title}" %>
<% @page_class = 'layout3' %>
<%= render :partial => 'admin/assets/sub_nav' %>
<div id="workspace">
  <div class="header">
    <h1><span class="pre">Ändra beskärning</span> <%= @asset.title %> - <%= "#{@cropping[:width]}x#{@cropping[:height]}px" %></h1>
  </div>
  <div id="content">
    <div id="crop">
      <%= image_tag @asset.version_url(:size => 'w500'), {
        :id => 'cropped_image',
        'data-original-width' => @asset.width,
        'data-original-height' => @asset.height,
        'data-cropped-width' => @cropping[:width],
        'data-cropped-height' => @cropping[:height],
        'data-cutout-x' => @cropping[:cutout_x],
        'data-cutout-y' => @cropping[:cutout_y],
        'data-cutout-width' => @cropping[:cutout_width],
        'data-cutout-height' => @cropping[:cutout_height]
      } %>
      <div id="preview_container" style="width:<%= @cropping[:width] %>px; height:<%= @cropping[:height] %>px;overflow:hidden;">
        <%= image_tag @asset.remote_url, :id => 'preview' %>
      </div>
    </div>
    <%= form_for [:admin, @asset], :as => :asset, :url => admin_asset_url(@asset) do |f| %>
      <%= hidden_field_tag(:return_to, params[:return_to]) if params[:return_to].present? %>
      <% "c#{@cropping[:width]}x#{@cropping[:height]}".tap do |cropping_name| %>
        <div style="display:none;">
          <label for="cutout_width">Bredd</label>
          <%= text_field_tag "asset[versions][#{cropping_name}][cutout_width]", nil, :id => 'cutout_width' %>
          <label for="cutout_height">Höjd</label>
          <%= text_field_tag "asset[versions][#{cropping_name}][cutout_height]", nil, :id => 'cutout_height' %>
          <label for="cutout_x">X</label>
          <%= text_field_tag "asset[versions][#{cropping_name}][cutout_x]", nil, :id => 'cutout_x' %>
          <label for="cutout_y">Y</label>
          <%= text_field_tag "asset[versions][#{cropping_name}][cutout_y]", nil, :id => 'cutout_y' %>
        </div>
        <div class="submit">
          <%= f.submit t(:save) %> <%= t('or') %> <%= link_to t('cancel'), edit_admin_asset_path(@asset) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/admin/assets/edit_cropping_offset.html.erb
<% @page_title = "Ändra beskärning: #{@asset.title}" %>
<div id="workspace">
  <div class="header">
    <h1><span class="pre">Ändra beskärning</span> <%= @asset.title %></h1>
  </div>
  <div id="content">
    <div id="c_1"><div class="inner">
      <%= image_tag @asset.version_url(:size => 'w500'), :id => 'cropped_image',
        'data-original-width' => @asset.width, 'data-original-height' => @asset.height,
        'data-cropped-width' => @cropping[:width], 'data-cropped-height' => @cropping[:height],
        'data-cutout-x' => @cropping[:cutout_x], 'data-cutout-y' => @cropping[:cutout_y],
        'data-cutout-width' => @cropping[:cutout_width], 'data-cutout-height' => @cropping[:cutout_height] %>
      <%= form_for [:admin, @asset], :as => :asset, :url => admin_asset_url(@asset) do |f| %>
        <% "c#{@cropping[:width]}x#{@cropping[:height]}".tap do |cropping_name| %>
          <%= hidden_field_tag "asset[versions][#{cropping_name}][cutout_width]", nil, :id => 'cutout_width' %>
          <%= hidden_field_tag "asset[versions][#{cropping_name}][cutout_height]", nil, :id => 'cutout_height' %>
          <%= hidden_field_tag "asset[versions][#{cropping_name}][cutout_x]", nil, :id => 'cutout_x' %>
          <%= hidden_field_tag "asset[versions][#{cropping_name}][cutout_y]", nil, :id => 'cutout_y' %>
          <%= f.submit t(:save) %>
        <% end %>
      <% end %>
    </div></div>
  </div>
</div>

app/views/admin/assets/index.html.erb
<% @page_title = "Bilder, video, ljud och dokument" %>
<% @page_class = 'layout3' %>
<%= render :partial => 'admin/assets/sub_nav' %>
<div id="workspace">
  <% if @current_tags.any? -%>
  <div class="header">
    <h1>Filer märkta med: <%= @current_tags.join(', ') %></h1>
  </div>
  <% else -%>
  <div class="header">
    <h1>Bilder, video, ljud och dokument</h1>
  </div>
  <div class="tools">
    <div class="add">
      <a href="<%= new_admin_asset_path %>" class="new"><%= t('.upload') %></a>
    </div>
    <%= form_tag admin_assets_path, :method => :get do |f| %>
    <div class="sort">
      <label for="filters_order_by">Sortering</label>
      <% current_scopes.except(:order_by).each do |filter, value| -%>
        <%= hidden_field_tag filter, value %>
      <% end -%>
        <%= select_tag 'order_by', options_for_select({ 'Datum' => 'created_at desc', 'A-Z' => 'title asc', 'Storlek' => 'size' }, current_scopes[:order_by]) %>
        <input type="submit" value="Välj" id="filters_order_by_submit" style="display:none">
    </div>
    <% end %>
  </div>
  <% end -%>
  <div id="content">
    <% if @content || @asset_usage %>
    <p>
      <span style="background:#ffb">Välj vilken bild/film du vill använda eller ladda upp en ny.</span>
      <%= link_to "Avbryt", previous_view_path(@context_params[:return_to]) %>
    </p>
    <% end %>

    <% if @assets.any? -%>
    <ul class="items thumbnails">
      <% @assets.each do |asset| %><li><div class="inner <%= asset.extension %>" id="asset_<%= asset.id %>">
        <% cache [ "v2", asset, "admin" ] do %>
          <a href="<%= edit_admin_asset_path(asset.id) %>">
          <% if asset.is_a?(ImageAsset) %>
            <%= image_tag asset.version_url(:size => '100'), :id => "asset_#{asset.id}" %>
          <% elsif asset.respond_to?(:thumbnail) and not asset.thumbnail.blank? %>
            <%= image_tag display_image_path(:size => '100', :id => asset.thumbnail, :format => asset.thumbnail.extension), :id => "asset_#{asset.id}" %>
          <% else %>
            <span class="icon"></span>
          <% end %>
          </a>
          <div class="title"><%= link_to asset.title, edit_admin_asset_path(asset.id) %></div>
          <div class="description<%= ' blank' if asset.description.blank? %>">
            <%= asset.description.blank? ? link_to('Ingen beskrivning, skriv en ...', edit_admin_asset_path(asset.id)) : truncate(asset.description, :length => 200) %>
          </div>
          <% if asset.tag_names.present? %>
          <div class="tags"><%= asset.tags.collect { |tag| @current_tags.include?(tag) ? tag.name : link_to(tag.name, admin_assets_path(:tags => [tag.name])) }.join(', ').html_safe -%></div>
          <% end %>
          <div class="meta">
            <span>Uppladdad</span> den <%= asset.created_at.strftime("%d %b %Y") %>
            <% if !asset.created_by.nil? && asset.created_by.respond_to?(:name) -%>
            <span>av</span> <%= asset.created_by.name %>
            <% end -%>
          </div>
          <div class="edit">
            <%= link_to t(:edit), edit_admin_asset_path(asset.id, :return_to => request.path+"#asset_#{asset.id}") %>
            <%= link_to t(:destroy), admin_asset_path(asset.id), class: 'delete', data: { confirm: "Är du säker att du vill ta bort filen? Den kommer försvinna från alla sidor. Du kan INTE ångra dig." }, method: :delete %>
          </div>
        <% end %>
        <% if @create_callback.present? %>
          <div class="add">
            <%= render :partial => 'create_callback_form', :locals => { :create_callback => @create_callback, :asset => asset} %>
          </div>
        <% end %>
      </div></li>
      <% end %>
    </ul>
    <%= paginate @assets %>
    <% end -%>
  </div>
</div>

app/views/admin/assets/search.html.erb
<% @page_title = "Sök filer och dokument" %>
<% @page_class = 'layout3' %>
<%= render :partial => 'admin/assets/sub_nav' %>
<div id="workspace">
  <div class="header">
    <h1>Sök filer och dokument</h1>
  </div>
  <div id="content">
    <div class="inner">
      <span class="notice">
        <% if @assets.any? %>
          <%= @assets.total_count %> filer hittades med sökningen ”<span class="query"><%= @query %></span>”.
          <%= link_to "Tillbaka", admin_assets_path, :class => 'back' %>
        <% else %>
          Inga filer hittades på din sökning. <%= link_to "Tillbaka till senaste filer", admin_assets_path, :class => 'back' %>
        <% end %>
      </span>
      <% if @assets.any? %>
      <ul class="items thumbnails">
        <% @assets.each do |asset| %>
          <li class="<%= cycle 'even', 'odd' %>"><div class="inner">
            <a href="<%= edit_admin_asset_path(asset) %>">
              <% if asset.is_a?(ImageAsset) %>
                <%= image_tag asset.version_url(:size => '100'), :id => "asset_#{asset.id}" %>
              <% elsif asset.respond_to?(:thumbnail) and not asset.thumbnail.blank? %>
                <%= image_tag display_image_path(:size => '100', :id => asset.thumbnail, :format => asset.thumbnail.extension), :id => "asset_#{asset.id}" %>
              <% else %>
                <span class="icon"></span>
              <% end %>
            </a>
            <div class="title"><%= link_to asset.title, edit_admin_asset_path(asset.id) %></div>
            <div class="description<%= ' blank' if asset.description.blank? %>">
              <%= asset.description.blank? ? link_to('Ingen beskrivning, skriv en ...', edit_admin_asset_path(asset.id)) : truncate(asset.description, :length => 200) %>
            </div>
            <% if asset.tag_names.present? %>
              <div class="tags"><%= asset.tags.collect { |tag| @current_tags.include?(tag) ? tag.name : link_to(tag.name, admin_assets_path(:tags => [tag.name])) }.join(', ').html_safe -%></div>
            <% end %>
            <div class="meta">
              <span>Uppladdad</span> den <%= asset.created_at.strftime("%d %b %Y") %>
              <% if !asset.created_by.nil? && asset.created_by.respond_to?(:name) -%>
                <span>av</span> <%= asset.created_by.name %>
              <% end -%>
            </div>
            <div class="edit">
              <%= link_to t(:edit), edit_admin_asset_path(asset.id, :return_to => request.path) %>
              <%= link_to t(:destroy), admin_asset_path(asset.id), class: 'delete', data: { confirm: "Är du säker att du vill ta bort filen? Den kommer försvinna från alla sidor. Du kan INTE ångra dig." }, method: :delete %>
            </div>
            <% if @create_callback.present? %>
              <div class="add">
                <%= render :partial => 'create_callback_form', :locals => {:create_callback => @create_callback, :asset => asset} %>
              </div>
            <% end %>
          </div></li>
        <% end %>
      </ul>
      <%= paginate @assets %>
      <% end %>
    </div>
  </div>
</div>