config/routes.rb
Rails.application.routes.draw do
  mount Porthos::Middleware::TagsAutocompleteApp.instance => '/admin/tags/autocomplete'

  filter :url_resolver

  resources :pages do
    collection do
      get 'categories'
    end
    member do
      get 'preview'
    end
  end
  get 'pages/:id/category' => 'pages#category', :as => 'pages_category'

  namespace :admin do
    root :to => 'dashboard#index'
    get '/login' => 'sessions#new', :as => 'login'
    get '/logout' => 'sessions#destroy', :as => 'logout'
    resources :sessions
    resources :users do
      collection do
        get 'admins'
        get 'search'
      end
    end

    resources :site_settings
    resources :redirects
    resources :tags
    resources :display_options do
      collection do
        put :sort
      end
    end

    resources :nodes do
      member do
        get "place"
        put "toggle"
        get "confirm_delete"
      end
      collection do
        put "sort"
      end
    end

    resources :link_lists do
      resources :links do
        collection do
          put 'sort'
        end
      end
    end

    resources :templates do
      resources :datum_templates do
        collection do
          put 'sort'
        end
      end
    end
    resources :page_templates do
      collection do
        put 'sort'
      end
    end
    resources :content_templates do
      collection do
        put 'sort'
      end
    end

    resources :items do
      collection do
        get "search"
        put "sort"
      end
      member do
        put "toggle"
        put "publish"
        get "confirm_delete"
      end
      resources :data do
        collection do
          put "sort"
        end
        member do
          put "toggle"
          get "settings"
        end
      end
    end

    resources :assets do
      collection do
        get 'search'
        get 'incomplete'
        put 'update_multiple'
      end
      member do
        get 'edit_cropping'
      end
    end
  end
end

app/views/layouts/admin/_account_nav.html.erb
<div id="account_nav">
  <ul>
    <li><%= link_to t(:settings, :scope => [:app, :views, :layouts, :admin, :account_nav]), admin_site_settings_path %></li>
    <li><%= link_to t(:my_account, :scope => [:app, :views, :layouts, :admin, :account_nav]), edit_admin_user_path(current_user) %></li>
    <li><%= link_to t(:logout, :scope => [:app, :views, :layouts, :admin, :account_nav]), admin_logout_path %></li>
  </ul>
</div>

app/views/layouts/admin/_main_nav.html.erb
<div id="main_nav">
  <ul>
    <li class="pages_index"><%= link_to "Sidor", admin_items_path %></li>
    <li class="nodes_index"><%= link_to "Navigation", admin_nodes_path %></li>
    <li class="assets_index"><%= link_to "Filarkiv", admin_assets_path %></li>
    <li class="users_index"><%= link_to t(:admins), admin_users_path %></li>
  </ul>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="<%= request_forgery_protection_token %>" id="authenticity-token" content="<%= form_authenticity_token %>">
  <meta name="csrf-token" content="<%= form_authenticity_token %>" />
  <meta name="csrf-param" content="authenticity_token" />
  <title><%= @page_title if @page_title %></title>
  <%= stylesheet_link_tag 'admin' %>
  <%= installation_specific_stylesheet_link_tag %>
</head>
<body<%= body_attributes.html_safe %>>
<%= flash_messages %>
<div id="nav">
  <%= render :partial => 'layouts/admin/account_nav' %>
  <%= render :partial => 'layouts/admin/main_nav' %>
</div>
<div id="wrap">
<%= yield %>
</div>

<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" %>
<%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js" %>
<%= javascript_include_tag 'admin' %>
</body>
</html>

app/views/layouts/admin/porthos.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">

<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="<%= request_forgery_protection_token %>" id="authenticity-token" content="<%= form_authenticity_token %>">
  <meta name="csrf-token" content="<%= form_authenticity_token %>" />
  <meta name="csrf-param" content="authenticity_token" />
  <title><%= @page_title if @page_title %></title>
  <%= stylesheet_link_tag 'porthos/elements', 'porthos/layout', 'porthos/wymeditor', 'application' %>
  <%= installation_specific_stylesheet_link_tag %>
</head>
<body<%= body_attributes.html_safe %>>
<%= flash_messages %>
<div id="nav">
  <%= render :partial => 'layouts/admin/account_nav' %>
  <%= render :partial => 'layouts/admin/main_nav' %>
</div>
<div id="wrap">
<%= yield %>
</div>
<%= javascript_fallback "http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js", "/javascripts/jquery-1.5.1.min.js", "typeof jQuery == 'undefined'" %>
<%= javascript_include_tag 'underscore.min.js', 'underscore.string.min.js' %>
<%= javascript_include_tag 'rails'  %>
<%= yield :javascripts %>
</body>
</html>

app/views/layouts/admin/sessions.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Porthos | Logga in</title>
  <%= stylesheet_link_tag 'admin' %>
</head>
<body<%= body_attributes %>>
<div id="wrap">
  <%= flash_messages %>
  <div id="header">
  </div>
  <div id="content">
    <%= yield %>
  </div>
</div>
</body>
</html>