config/routes.rb
Rails.application.routes.draw do
  mount Porthos::Middleware::TagsAutocompleteApp.instance => '/admin/tags/autocomplete'

  filter :url_resolver

  resources :pages do
    collection do
      get 'categories'
    end
    member do
      get 'preview'
    end
  end
  get 'pages/:id/category' => 'pages#category', :as => 'pages_category'

  namespace :admin do
    root :to => 'dashboard#index'
    get '/login' => 'sessions#new', :as => 'login'
    get '/logout' => 'sessions#destroy', :as => 'logout'
    resources :sessions
    resources :users do
      collection do
        get 'admins'
        get 'search'
      end
    end

    resources :site_settings
    resources :redirects
    resources :tags
    resources :display_options do
      collection do
        put :sort
      end
    end

    resources :nodes do
      member do
        get "place"
        put "toggle"
        get "confirm_delete"
      end
      collection do
        put "sort"
      end
    end

    resources :link_lists do
      resources :links do
        collection do
          put 'sort'
        end
      end
    end

    resources :templates do
      resources :datum_templates do
        collection do
          put 'sort'
        end
      end
    end
    resources :page_templates do
      collection do
        put 'sort'
      end
    end
    resources :content_templates do
      collection do
        put 'sort'
      end
    end

    resources :items do
      collection do
        get "search"
        put "sort"
      end
      member do
        put "toggle"
        put "publish"
        get "confirm_delete"
      end
      resources :data do
        collection do
          put "sort"
        end
        member do
          put "toggle"
          get "settings"
        end
      end
    end

    resources :assets do
      collection do
        get 'search'
        get 'incomplete'
        put 'update_multiple'
      end
      member do
        get 'edit_cropping'
      end
    end
  end
end

app/models/user.rb
class User
  include MongoMapper::Document
  plugin MongoMapper::Plugins::IdentityMap

  attr_reader :password

  key :first_name, String
  key :last_name, String
  key :username, String
  key :password_digest, String
  key :remember_me_token, String
  key :email, String

  key :phone, String
  key :cell_phone, String

  timestamps!
  # class accessor to be set and unset in the application controller
  # used to be able to access the current logged in user (controller variable) in models
  cattr_accessor :current

  validates :first_name,
            :presence => true
  validates :last_name,
            :presence => true
  validates :password,
            :confirmation => true,
            :presence => true,
            :if => :new?
  validates :username,
            :presence => true,
            :uniqueness => { :case_sensitive => false }
  validates :email,
            :presence => true,
            :uniqueness => { :case_sensitive => false }

  def password=(unencrypted_password)
    @password = unencrypted_password
    self.password_digest = BCrypt::Password.create(unencrypted_password) unless unencrypted_password.blank?
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(password_digest) == unencrypted_password
      self
    else
      false
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def short_name
    "#{first_name} #{!last_name.blank? ? last_name[0...1]+'.' : ''}"
  end

  def generate_remember_me_token!
    "#{id.to_s}#{SecureRandom.hex(24)}".tap do |token|
      self.update_attribute(:remember_me_token, token)
    end
  end

  class << self
    def authenticate(username, password)
      user = where(:username => username).first
      if user
        user.authenticate(password)
      else
        false
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  respond_to :html
  include Porthos::Admin

  def index
    @users = apply_scopes(User).page(params[:page])
    respond_with @users
  end

  def search
    query = params[:query]
    page  = params[:page] || 1
    @search = User.search do
      keywords(query)
      paginate :page => page
    end
    @query = query
    @page = page
    respond_to do |format|
      format.html
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "#{@user.name} #{t(:saved, :scope => [:app, :admin_general])}"
    end
    respond_with @user, :location => (params[:return_to] || admin_users_path)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "#{@user.name} #{t(:saved, :scope => [:app, :admin_general])}"
    end
    respond_with @user, :location => (params[:return_to] || admin_users_path)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "#{@user.name} #{t(:deleted, :scope => [:app, :admin_general])}"
    respond_with @user, :location => (params[:return_to] || admin_users_path)
  end

end

app/views/admin/users/_admin_form.html.erb
<%= render 'admin/shared/error_messages', :object => f.object %>
<%= hidden_field_tag 'role', 'Admin' %>

<div class="avatar">
<% if @user.avatar %>
  <%= image_tag(@user.avatar.version_url(:size => 'c60x60'), :class => "photo") %>
  <label for="user_file">Byt din profilbild</label>
<% else %>
  <label for="user_file">Profilbild</label>
<% end %>
<%= f.file_field :file, :size => 20 %>
</div>

<fieldset class="compact">
  <label for="user_first_name">Förnamn</label>
  <div class="fullwidth"><%= f.text_field :first_name, :autocomplete => "off" %></div>
  <label for="user_last_name">Efternamn</label>
  <div class="fullwidth"><%= f.text_field :last_name, :autocomplete => "off" %></div>
  <label for="user_email">E-post</label>
  <div class="fullwidth"><%= f.text_field :email, :autocomplete => "off" %></div>

  <label for="user_login">Användarnamn</label>
  <div class="fullwidth"><%= f.text_field :login, :autocomplete => "off" %></div>
  <label for="user_password">Lösenord</label>
  <div class="fullwidth"><%= f.password_field :password, :autocomplete => "off" %></div>
  <label for="user_password_confirmation">Bekräfta lösenord</label>
  <div class="fullwidth"><%= f.password_field :password_confirmation, :autocomplete => "off" %></div>

  <label for="user_phone">Telefon</label>
  <div class="fullwidth"><%= f.text_field :phone, :autocomplete => "off" %></div>
  <label for="user_cell_phone">Mobiltelefon</label>
  <div class="fullwidth"><%= f.text_field :cell_phone, :autocomplete => "off" %></div>
</fieldset>

app/views/admin/users/_form.html.erb
<%= render 'admin/shared/error_messages', :object => f.object %>

<fieldset class="compact">
  <label for="user_first_name">Förnamn</label>
  <div class="fullwidth"><%= f.text_field :first_name, :autocomplete => "off" %></div>
  <label for="user_last_name">Efternamn</label>
  <div class="fullwidth"><%= f.text_field :last_name, :autocomplete => "off" %></div>
  <label for="user_email">E-post</label>
  <div class="fullwidth"><%= f.text_field :email, :autocomplete => "off" %></div>

  <label for="username">Användarnamn</label>
  <div class="fullwidth"><%= f.text_field :username, :autocomplete => "off" %></div>
  <label for="user_password">Lösenord</label>
  <div class="fullwidth"><%= f.password_field :password, :autocomplete => "off" %></div>
  <label for="user_password_confirmation">Bekräfta lösenord</label>
  <div class="fullwidth"><%= f.password_field :password_confirmation, :autocomplete => "off" %></div>

  <label for="user_phone">Telefon</label>
  <div class="fullwidth"><%= f.text_field :phone, :autocomplete => "off" %></div>
  <label for="user_cell_phone">Mobiltelefon</label>
  <div class="fullwidth"><%= f.text_field :cell_phone, :autocomplete => "off" %></div>
</fieldset>

app/views/admin/users/_sub_nav.html.erb
<div id="sub_nav">
  <% if Rails.application.config.use_fulltext_search %>
  <% form_tag search_admin_users_path, :method => 'get' do %>
  <div class="search">
    <div class="fullwidth">
      <%= text_field_tag :query, (@query ? @query : 'Sök efter användare'), :class => "search_query", :id=> "ref_search_query" %>
    </div>
    <%= submit_tag "Sök", :style => "display:none" %>
  </div>
  <% end %>
  <% end %>
</div>

app/views/admin/users/_user.html.erb
<div class="vcard main" id="user_<%= user.id %>">
  <span class="fn"><%= user.name %></span>
  <a class="email" title="Skicka e-post till <%= user.name %>" href="mailto:<%= user.email %>"><%= user.email %></a>
  <% unless user.phone.blank? and user.cell_phone.blank? -%>
  <span class="tel">
    <% unless user.phone.blank? -%>
    <span class="work">
      <span class="type">T:</span>
      <span class="value"><%= user.phone %></span>
    </span>
    <% end -%>
    <% unless user.cell_phone.blank? -%>
    <span class="cell">
      <span class="type">M:</span>
      <span class="value"><%= user.cell_phone %></span>
    </span>
    <% end -%>
  </span>
  <% end %>
  <span class="edit">
    <%= link_to t(:edit), edit_admin_user_path(user) %>
  </span>
</div>

app/views/admin/users/edit.html.erb
<% @page_title = "Användare > Ändra #{@user.name}" -%>
<div id="workspace">
  <div class="header">
    <h1><span class="pre">Ändra</span> <%= @user.name %></h1>
  </div>
  <div id="content">
    <div id="c_1"><div class="inner">
      <%= form_for @user, :url => admin_user_path(@user), :html => { :method => :put, :multipart => true, :autocomplete => "off" } do |f| %>
        <%= render :partial => "form", :locals => { :f => f } %>
        <div class="submit">
          <%= f.submit t(:save) %> eller <%= link_to "Avbryt", previous_view_path(admin_users_path) %>
        </div>
      <% end %>
    </div></div>
    <div id="c_2"><div class="inner">
    </div></div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% @page_title = "Användare" -%>
<% @page_class = 'layout3' %>
<%= render :partial => 'sub_nav' %>
<div id="workspace">
  <div class="header">
    <h1>Användare</h1>
  </div>
  <div class="tools">
    <div class="add">
      <%= link_to t('.add'), new_admin_user_path, :class => "new" %>
    </div>
  </div>
  <div id="content">
    <ul id="userslist">
    <% @users.each do |user| -%>
      <li>
        <%= render :partial => 'user', :locals => {:user => user} %>
      </li>
    <% end -%>
    </ul>
    <%= paginate @users %>
  </div>
</div>

app/views/admin/users/new.html.erb
<% @page_title = "Lägg till ny redaktör" -%>
<% @page_class = "A" -%>
<div id="workspace">
  <div class="header">
    <h1>Lägg till ny redaktör</h1>
  </div>
  <div id="content">
    <%= form_for @user, :url => admin_users_path, :html => { :multipart => true } do |f| %>
      <%= render :partial => "form", :locals => { :f => f } %>
      <div class="submit">
        <%= f.submit t(:save) %> eller <%= link_to "Avbryt", previous_view_path(admin_users_path) %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/search.html.erb
<% @page_title = "Användare - sökresultat" -%>
<% @page_class = 'layout3' %>
<%= render :partial => 'sub_nav' %>
<div id="workspace">
  <div class="header">
    <h1>Sökresultat för "<%= @query %>" (<%= @search.total %> träffar)</h1></h1>
  </div>
  <div id="content">
    <div class="inner">
      <ul id="userslist">
      <% @search.results.each do |user| -%>
        <li>
          <%= render :partial => 'user', :locals => {:user => user} %>
        </li>
      <% end -%>
      </ul>
    </div>
  </div>
</div>